---
branches:
  only:
    - master

env:
  global:
    # DOCKER_EMAIL
    - secure: "c9DNYwprizT/JWu8hTIbpepZGniAw1RGOcBS5GOriHq5sDGg0lG0pbu/vNTgpIvo4RetJGAKQrWXzPN1xMU4MjKHb7UiskUZVePSETU7NKSo4Xz3FWkFGvOGi43lng3MEgxAGRcrHQT3le/szSKigTzjBGINZp95zhrE94PAb/JpplBT1oh/YtTIqs9x+uZNfN39oiS8XAOWw/k/ZFAgxXwfvaAYXeT1O9eUvOP5FMBWLXgwHmM956LUp094Ef+DErNwN6dzFhqwoegDx5czXLjPrjBLq/iHTyBXcybQyZpzmUYadEE1fh2IeQtgKKHD0deabJ4qktqvZHWH54vnSmZO0VQehev+6D7dRfVgEzuP2ccbQxLnfwwqlT0X3xbH2Y2OIOtCnuf5t5pZRrE7hSRIkBH9R2PFKvd77YO1MZwB0cnhpVj3eWQFcoYf+KZaOKQer9jifKtCMpY+MMOE63k50B6ESPYGBvQcQ/Wyffrdo5sWolwxfGeEsqTp91e6TGQXOo5rq+Xoc4IhEtl9GWtR3yfdDRKZcmiAYyD04wQ8SXhQrRl22dq6x4bvwHwWWZ/TKqwyHsk8xHr8VRj2E9Yc4O6u0sqBFg4DNY31kuDI4iS0NcLJBTRX/qywCeqEb34GbfZPjsp1ljnkMSLso8hqASzZSaJeal/uADCku1c="
    # DOCKER_USER
    - secure: "KhRI+HvfzWUyJSFfmeG6K+NBtuXGoRg//sv6MixLm9OobaTD50boqNYJmlhg9KSE1BpsRcGVM6vDQS7t+ESlvCDmbkKZIivhGT2XommORO9PBsdkRSGXPvuNRfZ6Cx+axP1OASqQuBdVV9iyyCqdK+ffVurK7LnpxdyWJARZJV4TY/VlfK0YFh7IdjAcEzv9abQoEvh7UZnJaiDZhbnJUNY1JKmXvTDQieg02zwVKO9urMPZgEukgvqbCZw0VH9Oswh/42HGNfwGQUlyU9kAJn8WSrLybw7Ixu7uDVBAnB6+nuhLTWk237NbUadh3Bz4mzFhrSXMzRCJ8Lt+TxVyA9Z1c1QRImdtq+sw6CIK+KWF+jwOITvSanDziAp3GFCr/lPQ6CLmIAFvzwpLzk89wkMSJYX1zOerXmNapxv5umQEIzP4go5jCxKno7R3jApQo13xH3wzOWF14JvhFU6ek76vC5bXz6lLK8JUWkTI/gWjwQo8NrFE4XoACt246EAxrf95EnVNVyKBjYrmCx+BjW6RgwsEr54muN5WUV5MADeXpNB8I8rDcr8MmBqYzIJba2BeRNO09GXdb5FG2gijSEcPVCwhsFSqVtYslDEcxPyFcfckwTH4wTfRDm0S/n7Suw2cx/5bbIRf/kt1t22WYgtAOrKxWkNbG0rl6HACxuQ="
    # DOCKER_PASS
    - secure: "aNNKX9etZfim3/Ql3lIz4UUVxz70UPDG9OvzACkPnncXcXsBELEpsQ099LjBEBJS0L2uQJbLuCxKr1O/KoY/4sYtIk4pkSh0CM2myezPP/yiSC1FMShdtMuApNHm014Kh3guS3ta+IyrDx+4Sjt1cn3+0P8kWVGe9wDhyEiU1cACXrxfq4lBXUZuarLq0aEUt6Tv0yD2PgKGlLP4SAn54VwCXgjTok1aKJyFckOEOgu3m4y1ii56YyJuSM3CbBkKVjk1A8QrT2J2C4rrsn8bVtEXohPy5b28k4KQzL202WCnUShXlHdyL/RRv6MTG7UeC4/3o3P3+kapapeFzUnz0I2bfmIBygE07mhxKK1yU/iuFNimmSmsZ38dp/Km9FlPNhNtqixDYqAw3rlh4krbYWY8c783LOaiE58Ub0yMOHBpEv9PCjQP4l1jDHu3TpaSOZWTeZKHYuhtMpZqGBLjRLKXdohruEwP4SJK/YES3Bv+fquuojq+EegJf33Uo+IZDnPFRzGekj19bsjPrxIBzDVdRrQIaT4BDcHXs1g1+RjyW7JgbhB+iXDjX0wu+qDOMhU2RCJ503ucssTgKUPTcWm73G79SiyIKlc/QgsSogmiDgQd9bcm9FOCLttLDyHdRWlxCidKjjrAb4X3luiRQHlXjATmQL0cXL8mEs8tuII="
    - DOCKER_REPO=spreadspace/icecast

script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:latest
  ### build the new images
  - docker build -t $DOCKER_REPO:latest .
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:latest
